# services/hf_wrapper.py
import os
import requests
from dotenv import load_dotenv
import os

# Remove or comment out load_dotenv()
# load_dotenv()
HF_API_KEY = os.getenv("HF_API_KEY")
if not HF_API_KEY:
    raise ValueError("HF_API_KEY not found in .env")


API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct"
HEADERS = {"Authorization": f"Bearer {HF_API_KEY}"}

class HFGenerator:
    def enhance(self, prompt: str, max_tokens: int = 300) -> str:
        payload = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": max_tokens,
                "temperature": 0.3
            }
        }

        response = requests.post(API_URL, headers=HEADERS, json=payload)

        if response.status_code != 200:
            raise RuntimeError(
                f"Hugging Face API request failed: {response.status_code} {response.text}"
            )

        output = response.json()

        # Returns text generated by the model
        if isinstance(output, list) and "generated_text" in output[0]:
            return output[0]["generated_text"].strip()

        return str(output)
